# Generated by Django 3.2.6 on 2022-08-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseReview', '0002_auto_20220828_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(help_text='enter the name of the college', max_length=200),
        ),
    ]
