# Generated by Django 3.2.6 on 2022-08-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseReview', '0003_alter_college_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='college',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courseReview.college'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='major',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='courseReview.major'),
        ),
    ]
