# Generated by Django 3.2.6 on 2022-08-31 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseReview', '0006_alter_course_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='college',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseReview.college'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, to='courseReview.course'),
        ),
        migrations.AlterField(
            model_name='extenduser',
            name='major',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseReview.major'),
        ),
        migrations.AlterField(
            model_name='review',
            name='time',
            field=models.DateTimeField(auto_now_add=True, help_text='time the review edited'),
        ),
    ]
