# Generated by Django 3.2.6 on 2022-09-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseReview', '0008_college_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='web',
            field=models.URLField(blank=True, help_text='web used to verify the department', null=True, verbose_name='Official Website'),
        ),
    ]
